wp: 
  tag: 6.2.1-apache
db:
  tag: 5.6
  credentials: 
    rootPassword: password
    dbHost: cnews-mysql
    dbName: wp-camara
    dbUser: wp-user
    dbPassword: wp-pass
conf:
  serviceType: LoadBalancer