wp: 
  tag: 6.2.1-apache
db:
  tag: 5.6
  credentials: 
    rootPassword: root
    dbHost: wphost-mysql
    dbName: wordpress
    dbUser: wordpress
    dbPassword: mysql-pass
conf:
  serviceType: LoadBalancer