wp: 
  tag: 6.2.1-apache
  wordpressExtraConfigContent: |
    define('VIDEO_UPLOAD_DIR', '/var/www/html/wp-content/uploads/midias/video');
    define('VIDEO_UPLOAD_URL', 'http://localhost:8383/wp-content/uploads/midias/video');
    define('IMAGE_UPLOAD_DIR', '/var/www/html/wp-content/uploads/midias/image');
    define('IMAGE_UPLOAD_URL', 'http://localhost:8383/wp-content/uploads/midias/image');
    define('AUDIO_UPLOAD_DIR', '/var/www/html/wp-content/uploads/midias/audio');
    define('AUDIO_UPLOAD_URL', 'http://localhost:8383/wp-content/uploads/midias/audio');

db:
  tag: 5.6
  credentials: 
    rootPassword: password
    dbHost: cnews-mysql-service
    dbName: wp-camara
    dbUser: wp-user
    dbPassword: wp-pass
conf:
  serviceType: LoadBalancer