wp: 
  tag: 6.2.1-apache
db:
  tag: 5.6
  credentials: 
    rootPassword: root
    dbHost: cnews-mysql-deploy
    dbName: wp-camara
    dbUser: wp-camara
    dbPassword: mysqlpass
conf:
  serviceType: LoadBalancer