wp: 
  tag: 6.2.1-apache
db:
  tag: 5.6
  credentials: 
    rootPassword: root
    dbHost: wp-host-mysql
    dbName: wp-camara
    dbUser: wp-camara
    dbPassword: 123456sete
conf:
  serviceType: LoadBalancer