apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  labels:
    app: {{ .Release.Name }}-camara
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-wp
    tier: mysql-wp
  clusterIP: None