apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deploy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:{{ .Values.db.tag }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.db.credentials.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.db.credentials.dbName }}
        - name: MYSQL_USER
          value: {{ .Values.db.credentials.dbUser }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.db.credentials.dbPassword }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv