apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wp
    spec:
      containers:
      - name: wp
        image: wordpress:{{ .Values.wp.tag }}
        ports:
        - containerPort: 80
          name: wp
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv
        resources: {}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.db.credentials.dbHost }}
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.db.credentials.dbName }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.db.credentials.dbPassword }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.db.credentials.dbUser }}
        - name: WORDPRESS_EXTRA_WP_CONFIG_CONTENT
          value: {{ .Values.wp.wordpressExtraConfigContent }}
        - name: WP_AMBIENTE
          value: tes