apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wp-service
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Release.Name }}-wp
    tier: frontend
  type: {{ .Values.conf.serviceType }}
  