apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-camara-service
spec:
  selector:
    app: {{ .Release.Name }}-camara
    tier: frontend
  type: {{ .Values.conf.serviceType }}
  ports:
    - port: 80
    targetPort: 8383